# ==============================================================================
# CnSS User ORM Models
# SQLAlchemy models for user identity and channel access control.
# Maps to the 'users' and 'user_channel_scopes' tables in TimescaleDB.
# ==============================================================================

import uuid
from datetime import datetime
from typing import List

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.models.base import Base


# --- User Model ---
# Represents an authenticated user with role-based access control.
class User(Base):
    """
    ORM model for the 'users' table.
    Stores identity, hashed password, and role for authorization.
    """

    __tablename__ = "users"

    # Primary key: UUID generated by PostgreSQL
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=func.gen_random_uuid(), comment="Unique user identifier"
    )

    # Username must be unique and not null
    username: Mapped[str] = mapped_column(
        String(50), unique=True, nullable=False, comment="Unique username for authentication"
    )

    # Argon2id password hash (never store plaintext)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False, comment="Argon2id password hash")

    # Role-Based Access Control: strictly limited to 'admin' or 'viewer'
    role: Mapped[str] = mapped_column(String(20), nullable=False, comment="User role: 'admin' or 'viewer'")

    # Timestamp of user creation
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Timestamp when the user was created",
    )

    # --- Relationships ---
    # One-to-many relationship with channel scopes
    channel_scopes: Mapped[List["UserChannelScope"]] = relationship(
        "UserChannelScope", back_populates="user", cascade="all, delete-orphan", lazy="selectin"
    )

    # --- Constraints ---
    __table_args__ = (CheckConstraint("role IN ('admin', 'viewer')", name="check_user_role_valid"),)

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<User(id={self.id}, username={self.username}, role={self.role})>"


# --- User Channel Scope Model ---
# Represents the many-to-many relationship between users and channels.
# Viewers are restricted to channels listed in this table.
class UserChannelScope(Base):
    """
    ORM model for the 'user_channel_scopes' table.
    Defines which channels a 'viewer' user can access.
    """

    __tablename__ = "user_channel_scopes"

    # Composite primary key: user_id + channel_id
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
        comment="Reference to the user",
    )

    channel_id: Mapped[str] = mapped_column(String, primary_key=True, comment="Channel identifier the user can access")

    # --- Relationships ---
    # Many-to-one relationship back to the user
    user: Mapped["User"] = relationship("User", back_populates="channel_scopes")

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<UserChannelScope(user_id={self.user_id}, channel_id={self.channel_id})>"
