name: ⚙️ PBI
description: Template for technical tasks, DevOps, documentation, or refactoring
title: "[PBI] Short descriptive title"
labels: ["pbi", "technical"]
body:
  - type: markdown
    attributes:
      value: |
        <!-- **Project Fields Reminder:** -->
        <!-- Please ensure you fill out the **milestone**, **mvp version**, **story points**, **priority**, and **pbi type** in the **Project field** of the issue (located in the right sidebar). -->
  - type: textarea
    id: description
    attributes:
      label: Description & Context
      description: "What needs to be done and why? Link to related User Stories if applicable."
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: "Define clear completion criteria using Given/When/Then format."
      value: |
        #### AC 1
        - [ ] ...

        #### AC 2
        - [ ] ...
        
    validations:
      required: true
  - type: input
    id: reviewer
    attributes:
      label: Assigned Reviewer
      placeholder: "@username"