# ==============================================================================
# Initial Database Schema Migration
# Creates the foundational tables for user management, channel registry,
# and role-based access control (RBAC) scopes.
# Strictly aligns with the TimescaleDB schema defined in architecture.md §3.1
# and the SQLAlchemy ORM models in core/models/users.py and core/models/channels.py.
# ==============================================================================

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# --- Revision Identifiers ---
# Auto-generated identifiers used by Alembic to track migration history and order.
# '001' denotes the initial schema setup for the CnSS backend.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Upgrade Operations ---
# Applies schema changes to transition the database to this revision.
# Creates tables, constraints, and indexes required for authentication and data routing.
def upgrade() -> None:
    # ==========================================================================
    # Users Table
    # Stores identity, hashed password, and role for authorization.
    # Mirrors core.models.users.User ORM model.
    # ==========================================================================
    op.create_table(
        "users",
        # Primary key: UUID generated by PostgreSQL gen_random_uuid()
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        # Unique username for authentication (max 50 chars)
        sa.Column("username", sa.String(50), unique=True, nullable=False),
        # Argon2id password hash (never store plaintext)
        sa.Column("password_hash", sa.String(255), nullable=False),
        # Role-Based Access Control: strictly limited to 'admin' or 'viewer'
        sa.Column("role", sa.String(20), nullable=False),
        # Timestamp of user creation (auto-set by database)
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # Enforce valid role values at the database level (defense in depth)
    op.create_check_constraint(
        "check_user_role_valid",
        "users",
        "role IN ('admin', 'viewer')",
    )

    # ==========================================================================
    # Channels Table (Persistent Registry)
    # Acts as the "cold" registry for channel metadata.
    # Real-time status is served from Redis; this table is updated by the
    # Reporting Worker every 1 second for historical records and audit logs.
    # Mirrors core.models.channels.Channel ORM model.
    # ==========================================================================
    op.create_table(
        "channels",
        # Primary key: channel identifier (trusted assertion from Communication Node)
        sa.Column("channel_id", sa.String(), primary_key=True),
        # Timestamp of the channel's first discovery/creation in the system
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Timestamp of the last successfully processed telemetry batch
        # Nullable because a newly created channel might not have received traffic yet
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        # Accumulated count of dropped packets (updated by Reporting Worker)
        sa.Column("dropped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        # Activity flag toggled by the Reporting Worker based on last_activity_at
        # False if no activity for > 5 seconds, True otherwise
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )

    # ==========================================================================
    # User Channel Scopes Table (RBAC)
    # Defines which channels a 'viewer' user can access.
    # Admins bypass this table entirely (unrestricted access).
    # Mirrors core.models.users.UserChannelScope ORM model.
    # ==========================================================================
    op.create_table(
        "user_channel_scopes",
        # Reference to the user (cascades on user deletion)
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        # Channel identifier the user can access
        sa.Column("channel_id", sa.String(), primary_key=True),
    )


# --- Downgrade Operations ---
# Reverts schema changes to safely roll back to the previous state.
# Drops tables in reverse dependency order to satisfy foreign key constraints.
def downgrade() -> None:
    # Drop the RBAC scopes table first (depends on users)
    op.drop_table("user_channel_scopes")

    # Drop the channels registry table
    op.drop_table("channels")

    # Drop the users table last (no remaining dependencies)
    op.drop_table("users")
