/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Authentication
         * @description Authenticate user and issue JWT token with role and scope information.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful authentication */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Bad request (missing fields) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Health Check
         * @description Verify operational status of the CnSS and aggregate channel statistics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description System is unhealthy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Accessible Channels
         * @description List all channels accessible to the authenticated user.
         *     For `viewer`, the list is filtered by JWT `scope`.
         *     For `admin`, all known channels are returned.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of channels */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Specific Channel Activity Status
         * @description REST fallback for a specific channel's activity indicator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifier of the channel to query. */
                    channel_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelStatusResponse"];
                    };
                };
                /** @description Forbidden (user has no access to this channel) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Real-time Telemetry Stream (WebSocket)
         * @description Upgrades to WebSocket for real-time push stream, scoped to a specific channel.
         *     Auth via query parameters `?token={{access_token}}&channel_id={{channel_id}}`.
         *
         *     **Connection Lifecycle & Close Codes:**
         *     1. MUI opens WebSocket connection with `token` and `channel_id`.
         *     2. CnSS validates token. On failure, closes with code `4001` (invalid_token).
         *     3. CnSS checks if the `channel_id` query parameter is present in the URL. On failure, closes with code `4002` (missing_channel).
         *     4. CnSS checks access to `channel_id` via JWT scope. On failure, closes with code `4003` (channel_forbidden).
         *     5. CnSS checks if the provided `channel_id` value exists in the registry. On failure, closes with code `4004` (channel_not_found).
         *     6. CnSS pushes `telemetry_update` frames (2-10 Hz).
         *     7. **Keep-Alive:** CnSS sends periodic `ping` frames. MUI must respond with `pong`.
         *     8. If no telemetry from CN for 5000ms, CnSS sends `is_active: false`.
         *
         *     *Security Note: CnSS MUST NOT log the full request URL to prevent token leakage.*
         */
        get: {
            parameters: {
                query: {
                    /** @description Bearer token for authentication */
                    token: string;
                    /** @description Identifier of the channel to subscribe to */
                    channel_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols to WebSocket */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example secretpassword
             */
            password: string;
        };
        LoginResponse: {
            /**
             * @description JWT token for authenticated requests.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
            /**
             * @description Token lifetime in seconds.
             * @example 86400
             */
            expires_in?: number;
            /**
             * Format: date-time
             * @example 2026-06-18T12:00:00Z
             */
            issued_at?: string;
            /**
             * @example admin
             * @enum {string}
             */
            role?: "admin" | "viewer";
            /**
             * @description List of accessible channel_ids.
             * @example [
             *       "bridge-berlin-01",
             *       "bridge-prague-01"
             *     ]
             */
            scope?: string[];
        };
        ErrorResponse: {
            /** @example invalid_credentials */
            error?: string;
            /** @example Invalid username or password. */
            message?: string;
        };
        HealthResponse: {
            /**
             * @example healthy
             * @enum {string}
             */
            status?: "healthy" | "degraded" | "unhealthy";
            components?: {
                /**
                 * @example active
                 * @enum {string}
                 */
                cnss?: "active" | "inactive" | "error";
            };
            /**
             * @description Number of channels currently reporting telemetry.
             * @example 3
             */
            channels_active?: number;
            /**
             * @description Total number of channels known to CnSS.
             * @example 4
             */
            channels_total?: number;
            /**
             * Format: date-time
             * @example 2026-06-17T12:00:00Z
             */
            timestamp?: string;
        };
        ChannelsResponse: {
            channels?: components["schemas"]["ChannelStatusResponse"][];
            /** @example 2 */
            total?: number;
        };
        ChannelStatusResponse: {
            /** @example bridge-berlin-01 */
            channel_id?: string;
            /** @example true */
            is_active?: boolean;
            /**
             * Format: date-time
             * @example 2026-06-17T12:00:00Z
             */
            last_activity_timestamp?: string;
        };
        /** @description Payload sent from CN to CnSS over UDP. */
        TelemetryBatch: {
            /**
             * @description Identifier of the monitored channel/bridge. Used by CnSS to route the batch.
             * @example bridge-berlin-01
             */
            channel_id?: string;
            /**
             * @description Monotonically increasing sequence number per channel.
             * @example 1042
             */
            sequence?: number;
            /** @example 500 */
            window_ms?: number;
            direction_out?: {
                /** @example 150 */
                packets?: number;
            };
            direction_in?: {
                /** @example 140 */
                packets?: number;
            };
            /**
             * Format: date-time
             * @example 2026-06-17T12:00:00Z
             */
            timestamp?: string;
        };
        /** @description Payload pushed from CnSS to MUI over WebSocket. */
        TelemetryUpdate: {
            /** @example telemetry_update */
            type?: string;
            /** @example bridge-berlin-01 */
            channel_id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example 500 */
            window_ms?: number;
            /**
             * @description Number of lost UDP datagrams between the previous and current batch for this channel.
             * @example 0
             */
            dropped_batches?: number;
            metrics?: {
                direction_out?: {
                    /**
                     * Format: float
                     * @example 300
                     */
                    packets_per_sec?: number;
                    /** @example 150 */
                    packets?: number;
                };
                direction_in?: {
                    /**
                     * Format: float
                     * @example 280
                     */
                    packets_per_sec?: number;
                    /** @example 140 */
                    packets?: number;
                };
            };
            /**
             * Format: date-time
             * @description Original timestamp from the CN batch.
             * @example 2026-06-17T12:00:00Z
             */
            timestamp?: string;
            /**
             * Format: date-time
             * @description Server time at CnSS when the UDP datagram was received.
             * @example 2026-06-17T12:00:00.050Z
             */
            received_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
