/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Authentication
         * @description Authenticate user and issue JWT access token. Sets `refresh_token` as an HttpOnly cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful authentication */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Access Token
         * @description Issues a new short-lived access token using the long-lived refresh token stored in the HttpOnly cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New access token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshTokenResponse"];
                    };
                };
                /** @description Refresh token missing, invalid, expired, or revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Logout
         * @description Invalidates the current session by revoking the refresh token in Redis and clearing the cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully logged out */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Health Check
         * @description Verify operational status of the CnSS and aggregate channel statistics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description System is unhealthy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Accessible Channels
         * @description List all channels accessible to the authenticated user.
         *     For `viewer`, the list is filtered by JWT `scope`.
         *     For `admin`, all known channels are returned.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of channels */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelsListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Specific Channel Activity Status
         * @description REST fallback for a specific channel's activity indicator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifier of the channel to query. */
                    channel_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelStatus"];
                    };
                };
                /** @description Forbidden (user has no access to this channel) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical Telemetry Data (Line Chart)
         * @description Lazy-loads historical telemetry data for the Channel Line Chart.
         *     CnSS dynamically calculates the optimal `time_bucket` interval (approx 1400 points)
         *     based on the requested `period_sec` to ensure smooth chart rendering.
         */
        get: {
            parameters: {
                query: {
                    /** @description Duration of the time window in seconds (e.g., 3600 for 1 hour, 86400 for 24h). */
                    period_sec: number;
                    /** @description Start of the time range (ISO 8601). If omitted, defaults to `now - period_sec`. */
                    start_time?: string;
                };
                header?: never;
                path: {
                    /** @description Identifier of the channel to query. */
                    channel_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated historical points */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelHistoryResponse"];
                    };
                };
                /** @description Bad request (invalid start_time or exceeds retention) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/hosts/{host_ip}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical Host Rx/Tx Data
         * @description Lazy-loads historical Rx/Tx rate data for a specific Host Line Chart.
         *     CnSS dynamically calculates the optimal `time_bucket` interval
         *     based on the requested `period_sec` to ensure smooth chart rendering.
         */
        get: {
            parameters: {
                query: {
                    /** @description Duration of the time window in seconds. */
                    period_sec: number;
                    /** @description Start of the time range (ISO 8601). If omitted, defaults to `now - period_sec`. */
                    start_time?: string;
                };
                header?: never;
                path: {
                    /** @description Identifier of the channel to query. */
                    channel_id: string;
                    /** @description IP address of the host (IPv4/IPv6). */
                    host_ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated host historical points */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HostHistoryResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Channel or host not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Real-time WebSocket Gateway
         * @description Upgrades to WebSocket for real-time push streams, scoped to a specific channel.
         *     Auth via query parameters `?token={{access_token}}&channel_id={{channel_id}}`.
         *
         *     **Control Messages:**
         *     MUI must send a JSON text frame to subscribe to specific data targets.
         *     See `WSControlMessage` schema for details on targets and parameters.
         */
        get: {
            parameters: {
                query: {
                    /** @description Bearer token for authentication */
                    token: string;
                    /** @description Identifier of the channel to subscribe to */
                    channel_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols to WebSocket */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example secretpassword
             */
            password: string;
        };
        TokenResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            /**
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
            /** @example 86400 */
            expires_in: number;
            /** Format: date-time */
            issued_at: string;
            /** @enum {string} */
            role: "admin" | "viewer";
            /** @description List of accessible channel_ids. Empty for admin. */
            scope: string[];
        };
        RefreshTokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            expires_in: number;
            /** Format: date-time */
            issued_at: string;
        };
        LogoutResponse: {
            /** @example Successfully logged out. */
            message: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "unhealthy";
            components: {
                [key: string]: "active" | "error";
            };
            channels_active: number;
            channels_total: number;
            /** Format: date-time */
            timestamp: string;
        };
        ChannelStatus: {
            channel_id: string;
            is_active: boolean;
            /** Format: date-time */
            last_activity_timestamp: string | null;
        };
        ChannelsListResponse: {
            channels: components["schemas"]["ChannelStatus"][];
            total: number;
        };
        ChannelHistoryResponse: {
            /** @description Identifier of the queried channel. */
            channel_id: string;
            /** @description Requested period duration in seconds. */
            period_sec: number;
            /**
             * Format: date-time
             * @description Actual start of the returned time range.
             */
            start_time: string;
            /**
             * Format: date-time
             * @description Actual end of the returned time range.
             */
            end_time: string;
            /** @description The calculated time bucket size in seconds. */
            interval_sec: number;
            /** @description Array of aggregated data points. */
            points: components["schemas"]["HistoryPoint"][];
        };
        HistoryPoint: {
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the data point.
             */
            timestamp: string;
            /**
             * Format: float
             * @description Aggregated incoming packet rate.
             */
            packets_in_per_sec: number;
            /**
             * Format: float
             * @description Aggregated outgoing packet rate.
             */
            packets_out_per_sec: number;
            /** @description Channel activity status at this specific timestamp (Channel History only). */
            is_active: boolean;
        };
        HostHistoryResponse: {
            /** @description Identifier of the queried channel. */
            channel_id: string;
            /** @description IP address of the queried host. */
            host_ip: string;
            /** @description Requested period duration in seconds. */
            period_sec: number;
            /**
             * Format: date-time
             * @description Actual start of the returned time range.
             */
            start_time: string;
            /**
             * Format: date-time
             * @description Actual end of the returned time range.
             */
            end_time: string;
            /** @description The calculated time bucket size in seconds. */
            interval_sec: number;
            /** @description Array of aggregated data points. */
            points: components["schemas"]["HostHistoryPoint"][];
        };
        HostHistoryPoint: {
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the data point.
             */
            timestamp: string;
            /**
             * Format: float
             * @description Aggregated incoming packet rate for the host.
             */
            packets_in_per_sec: number;
            /**
             * Format: float
             * @description Aggregated outgoing packet rate for the host.
             */
            packets_out_per_sec: number;
        };
        ErrorResponse: {
            /**
             * @description Machine-readable error code
             * @example invalid_credentials
             */
            error: string;
            /**
             * @description Human-readable description
             * @example Invalid username or password.
             */
            message: string;
            /** @description Optional validation error details */
            details: Record<string, never>[];
        };
        /** @description Payload sent from CN to CnSS over UDP. */
        TelemetryBatch: {
            channel_id: string;
            /** @description Unix timestamp (seconds) */
            timestamp: number;
            /**
             * Format: int64
             * @description 64-bit monotonically increasing sequence number
             */
            sequence: number;
            window_ms: number;
            packets: components["schemas"]["PacketFlow"][];
        };
        PacketFlow: {
            /**
             * @description 0 for IN, 1 for OUT
             * @enum {integer}
             */
            direction: 0 | 1;
            src_ip: string;
            dst_ip: string;
            src_port: number;
            dst_port: number;
            /**
             * @description Protocol (e.g., TCP/UDP). Required for accurate host_top_ports protocol reporting.
             * @enum {string}
             */
            protocol: "TCP" | "UDP";
        };
        /**
         * @description Text frame sent from MUI to CnSS to manage WebSocket subscriptions.
         *     The `id` field is required and must be unique per subscription instance.
         *     The `params` object structure depends on the `target`.
         */
        WSControlMessage: {
            /** @enum {string} */
            action: "subscribe" | "unsubscribe";
            /** @description Client-generated unique identifier */
            id: string;
            channel_id: string;
            /** @enum {string} */
            target: "telemetry" | "hosts_table" | "host_details" | "host_top_destinations" | "host_top_ports";
            /**
             * @description Target-specific parameters. See schemas:
             *     - `telemetry`: `TelemetryParams`
             *     - `hosts_table`: `HostsTableParams`
             *     - `host_details`: `HostDetailsParams`
             *     - `host_top_destinations`: `HostTopDestinationsParams`
             *     - `host_top_ports`: `HostTopPortsParams`
             */
            params?: Record<string, never>;
        };
        TelemetryParams: {
            /**
             * Format: float
             * @description Aggregation time window in seconds. Defines the rolling window for `packets_per_sec` calculation.
             */
            window_sec: number;
        };
        HostsTableParams: {
            /** @description Aggregation time window in seconds (e.g., 300 for 5m, 900 for 15m). */
            period_sec: number;
            /**
             * @description Filter by network location (LAN or WAN), or null for all.
             * @enum {string|null}
             */
            location: "LAN" | "WAN" | null;
            /** @description Exact IP address match filter, or null. */
            ip: string | null;
            /** @enum {string} */
            sort_by: "location" | "ip" | "unique_destinations" | "tx" | "rx" | "last_activity";
            /** @enum {string} */
            sort_order: "asc" | "desc";
            /** @description Page size. */
            limit: number;
            /** @description Pagination offset. */
            offset: number;
        };
        HostDetailsParams: {
            /** @description IP address of the specific host. */
            host_ip: string;
            /** @description Aggregation window in seconds for real-time rate calculation. */
            period_sec?: number;
        };
        HostTopDestinationsParams: {
            /** @description IP address of the specific host. */
            host_ip: string;
            /** @description Aggregation time window in seconds. */
            period_sec?: number;
            /** @enum {string} */
            sort_by?: "ip" | "location" | "received" | "last_seen";
            /** @enum {string} */
            sort_order?: "asc" | "desc";
            /** @description Page size. */
            limit?: number;
            /** @description Pagination offset. */
            offset?: number;
        };
        HostTopPortsParams: {
            /** @description IP address of the specific host. */
            host_ip: string;
            /** @description Aggregation time window in seconds. */
            period_sec?: number;
            /** @enum {string} */
            sort_by?: "port" | "protocol" | "pps";
            /** @enum {string} */
            sort_order?: "asc" | "desc";
            /** @description Page size. */
            limit?: number;
            /** @description Pagination offset. */
            offset?: number;
        };
        TelemetryUpdate: {
            /** @enum {string} */
            type: "telemetry_update";
            id: string;
            channel_id: string;
            is_active: boolean;
            window_ms: number;
            dropped_batches: number;
            metrics: {
                direction_out: {
                    packets_per_sec: number;
                    packets: number;
                };
                direction_in: {
                    packets_per_sec: number;
                    packets: number;
                };
            };
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            received_at: string;
        };
        HostsTableUpdate: {
            /** @enum {string} */
            type: "hosts_table_update";
            id: string;
            channel_id: string;
            /** @enum {string} */
            target: "hosts_table";
            /** Format: date-time */
            timestamp: string;
            total_count: number;
            hosts: components["schemas"]["HostEntry"][];
        };
        HostEntry: {
            /** @enum {string} */
            location: "LAN" | "WAN";
            ip: string;
            unique_destinations: number;
            tx_per_sec: number;
            rx_per_sec: number;
            /** Format: date-time */
            last_activity: string;
        };
        HostDetailsUpdate: {
            /** @enum {string} */
            type: "host_details_update";
            id: string;
            channel_id: string;
            host_ip: string;
            /** Format: date-time */
            timestamp: string;
            tx_per_sec: number;
            rx_per_sec: number;
        };
        HostTopDestinationsUpdate: {
            /** @enum {string} */
            type: "host_top_destinations_update";
            id: string;
            channel_id: string;
            host_ip: string;
            /** Format: date-time */
            timestamp: string;
            total_count: number;
            destinations: components["schemas"]["DestinationEntry"][];
        };
        DestinationEntry: {
            ip: string;
            /** @enum {string} */
            location: "LAN" | "WAN";
            received_per_sec: number;
            /** Format: date-time */
            last_seen: string;
        };
        HostTopPortsUpdate: {
            /** @enum {string} */
            type: "host_top_ports_update";
            id: string;
            channel_id: string;
            host_ip: string;
            /** Format: date-time */
            timestamp: string;
            total_count: number;
            ports: components["schemas"]["PortEntry"][];
        };
        PortEntry: {
            port: number;
            /** @enum {string} */
            protocol: "TCP" | "UDP";
            packets_per_sec: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
