/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Authentication
         * @description Authenticate user and issue JWT token with role and scope information.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful authentication */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Bad request (missing fields) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Health Check
         * @description Verify operational status of the CnSS and aggregate channel statistics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description System is unhealthy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Accessible Channels
         * @description List all channels accessible to the authenticated user.
         *     For `viewer`, the list is filtered by JWT `scope`.
         *     For `admin`, all known channels are returned.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of channels */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Specific Channel Activity Status
         * @description REST fallback for a specific channel's activity indicator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifier of the channel to query. */
                    channel_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Channel status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelStatusResponse"];
                    };
                };
                /** @description Forbidden (user has no access to this channel) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channel/{channel_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical Telemetry Data (Line Chart)
         * @description Lazy-loads historical telemetry data for the Line Chart.
         *     CnSS dynamically calculates the optimal `time_bucket` interval based on the requested period.
         */
        get: {
            parameters: {
                query: {
                    /** @description Time period to query. */
                    period: "1h" | "24h" | "7d" | "30d";
                };
                header?: never;
                path: {
                    channel_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated historical points */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Channel not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Real-time Telemetry Stream (WebSocket)
         * @description Upgrades to WebSocket for real-time push stream, scoped to a specific channel.
         *     Auth via query parameters `?token={{access_token}}&channel_id={{channel_id}}`.
         *
         *     **Connection Lifecycle & Close Codes:**
         *     1. MUI opens WebSocket connection with `token` and `channel_id`.
         *     2. CnSS validates token. On failure, closes with code `4001` (invalid_token).
         *     3. CnSS checks if the `channel_id` query parameter is present in the URL. On failure, closes with code `4002` (missing_channel).
         *     4. CnSS checks access to `channel_id` via JWT scope. On failure, closes with code `4003` (channel_forbidden).
         *     5. CnSS checks if the provided `channel_id` value exists in the registry. On failure, closes with code `4004` (channel_not_found).
         *     6. CnSS pushes `telemetry_update` frames at 1 Hz (aggregated by Reporting Worker from TimescaleDB).
         *     7. **Keep-Alive:** CnSS sends periodic `ping` frames. MUI must respond with `pong`.
         *     8. If no telemetry from CN for 5000ms, CnSS sends `is_active: false`.
         *     9. **Control Messages:** MUI can send JSON text frames to manage subscriptions for host tables (e.g., `{"action": "subscribe", "target": "lan_hosts"}`).
         *     10. **Host Updates:** CnSS pushes `hosts_update` frames to subscribed clients containing real-time LAN/WAN host statistics.
         *
         *     *Security Note: CnSS MUST NOT log the full request URL to prevent token leakage.*
         */
        get: {
            parameters: {
                query: {
                    /** @description Bearer token for authentication */
                    token: string;
                    /** @description Identifier of the channel to subscribe to */
                    channel_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols to WebSocket */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example secretpassword
             */
            password: string;
        };
        LoginResponse: {
            /**
             * @description JWT token for authenticated requests.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
            /**
             * @description Token lifetime in seconds.
             * @example 86400
             */
            expires_in?: number;
            /**
             * Format: date-time
             * @example 2026-06-18T12:00:00Z
             */
            issued_at?: string;
            /**
             * @example admin
             * @enum {string}
             */
            role?: "admin" | "viewer";
            /**
             * @description List of accessible channel_ids.
             * @example [
             *       "bridge-berlin-01",
             *       "bridge-prague-01"
             *     ]
             */
            scope?: string[];
        };
        ErrorResponse: {
            /** @example invalid_credentials */
            error?: string;
            /** @example Invalid username or password. */
            message?: string;
        };
        HealthResponse: {
            /**
             * @example healthy
             * @enum {string}
             */
            status?: "healthy" | "degraded" | "unhealthy";
            components?: {
                /**
                 * @example active
                 * @enum {string}
                 */
                cnss?: "active" | "inactive" | "error";
            };
            /**
             * @description Number of channels currently reporting telemetry.
             * @example 3
             */
            channels_active?: number;
            /**
             * @description Total number of channels known to CnSS.
             * @example 4
             */
            channels_total?: number;
            /**
             * Format: date-time
             * @example 2026-06-17T12:00:00Z
             */
            timestamp?: string;
        };
        ChannelsResponse: {
            channels?: components["schemas"]["ChannelStatusResponse"][];
            /** @example 2 */
            total?: number;
        };
        ChannelStatusResponse: {
            /** @example bridge-berlin-01 */
            channel_id?: string;
            /** @example true */
            is_active?: boolean;
            /**
             * Format: date-time
             * @example 2026-06-17T12:00:00Z
             */
            last_activity_timestamp?: string;
        };
        /** @description Raw metadata for a single observed packet. */
        PacketMetadata: {
            /**
             * @description 0 for IN, 1 for OUT.
             * @example 0
             * @enum {integer}
             */
            direction?: 0 | 1;
            /**
             * @description Source IP address (IPv4/IPv6).
             * @example 192.168.1.100
             */
            src_ip?: string;
            /**
             * @description Destination IP address (IPv4/IPv6).
             * @example 8.8.8.8
             */
            dst_ip?: string;
            /**
             * @description Source port.
             * @example 12345
             */
            src_port?: number;
            /**
             * @description Destination port.
             * @example 53
             */
            dst_port?: number;
        };
        /**
         * @description Payload sent from CN to CnSS over UDP.
         *     Contains raw packet metadata for a specific time window.
         *     CN must keep `window_ms` small enough to ensure the JSON payload fits within a single UDP datagram (ideally < 1400 bytes to avoid IP fragmentation).
         */
        TelemetryBatch: {
            /**
             * @description Identifier of the monitored channel/bridge. Used by CnSS to route the batch.
             * @example bridge-berlin-01
             */
            channel_id?: string;
            /**
             * @description Unix timestamp (seconds) of the window start.
             * @example 1718625600
             */
            timestamp?: number;
            /**
             * @description Monotonically increasing sequence number per channel. Used by CnSS to detect dropped UDP datagrams.
             * @example 1042
             */
            sequence?: number;
            /**
             * @description Duration of the batching window in milliseconds. Must be kept small enough to ensure the JSON fits within the UDP MTU (< 1400 bytes).
             * @example 50
             */
            window_ms?: number;
            /** @description Array of raw packet metadata captured during the window. */
            packets?: components["schemas"]["PacketMetadata"][];
        };
        /** @description Payload pushed from CnSS to MUI over WebSocket. Aggregated by the Reporting Worker from TimescaleDB at 1 Hz. */
        TelemetryUpdate: {
            /** @example telemetry_update */
            type?: string;
            /** @example bridge-berlin-01 */
            channel_id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example 50 */
            window_ms?: number;
            /**
             * @description Number of lost UDP datagrams between the previous and current batch for this channel.
             * @example 0
             */
            dropped_batches?: number;
            metrics?: {
                direction_out?: {
                    /**
                     * Format: float
                     * @example 300
                     */
                    packets_per_sec?: number;
                    /** @example 15 */
                    packets?: number;
                };
                direction_in?: {
                    /**
                     * Format: float
                     * @example 280
                     */
                    packets_per_sec?: number;
                    /** @example 14 */
                    packets?: number;
                };
            };
            /**
             * Format: date-time
             * @description Original timestamp from the latest CN batch.
             * @example 2026-06-17T12:00:00Z
             */
            timestamp?: string;
            /**
             * Format: date-time
             * @description Server time at CnSS when the aggregation was generated by the Reporting Worker.
             * @example 2026-06-17T12:00:00.050Z
             */
            received_at?: string;
        };
        HistoryResponse: {
            channel_id?: string;
            /** @enum {string} */
            period?: "1h" | "24h" | "7d" | "30d";
            /** @description The calculated time bucket size in seconds. */
            interval_sec?: number;
            points?: components["schemas"]["HistoryPoint"][];
        };
        HistoryPoint: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: float */
            packets_in_per_sec?: number;
            /** Format: float */
            packets_out_per_sec?: number;
            is_active?: boolean;
        };
        /** @description Text frame sent from MUI to CnSS to manage WebSocket subscriptions. */
        WSControlMessage: {
            /** @enum {string} */
            action?: "subscribe" | "unsubscribe";
            /** @enum {string} */
            target?: "lan_hosts" | "wan_hosts";
            /**
             * @description Required if action is 'subscribe'.
             * @enum {string}
             */
            sort_by?: "sent" | "received" | "last_seen";
            /** @description Required if action is 'subscribe'. Default 5. */
            limit?: number;
        };
        /** @description JSON frame pushed from CnSS to MUI with real-time host table data. */
        HostsUpdate: {
            /** @example hosts_update */
            type?: string;
            /** @enum {string} */
            target?: "lan_hosts" | "wan_hosts";
            channel_id?: string;
            /** Format: date-time */
            timestamp?: string;
            hosts?: components["schemas"]["HostEntry"][];
        };
        HostEntry: {
            ip?: string;
            /** Format: float */
            sent_per_sec?: number;
            /** Format: float */
            received_per_sec?: number;
            /** Format: date-time */
            last_seen?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
