services:
  # =========================================
  # PRODUCTION
  # =========================================
  mui:
    image: mui:prod
    container_name: mui

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"
    
    restart: unless-stopped

    env_file:
      - .env

    profiles:
      - prod
  

  # =========================================
  # DEVELOPMENT
  # =========================================
  mui-dev:
    image: mui:dev
    container_name: mui-dev

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "5173:5173"

    develop:
      watch:
        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./.env
        
        - action: rebuild
          path: ./vite.config.ts

        - action: sync
          path: .
          target: /app
          ignore:
            - nginx.conf
    
    restart: unless-stopped

    env_file:
      - .env
    
    profiles:
      - dev